const toolTipElements = [
    {
      id: 1,
      name: "General Apparatus",
      items: [
        "Round Bottom Flask",
        "Condenser",
        "Dropping Funnel",
        "Bunsen Burner",
        "Magnetic Stirrer",
        "Test Tube",
        "Measuring Cylinder",
        "Balance",
        "Filter Paper",
        "Pipette",
        "Retort Stand and Clamps",
      ],
    },
    {
      id: 2,
      name: "Reaction Vessels",
      items: [
        "Erlenmeyer Flask",
        "Beaker",
        "Graduated Cylinder",
        "Crucible",
        "Volumetric Flask",
        "Petri Dish",
      ],
    },
    {
      id: 3,
      name: "Catalysts & Reagents",
      items: [
        "Anhydrous AlCl3",
        "Sulfuric Acid",
        "Hydrochloric Acid",
        "Sodium Hydroxide",
        "Acetone",
        "Ethanol",
        "Benzene",
      ],
    },
    {
      id: 4,
      name: "External Conditions",
      items: [
        "Water Bath",
        "Ice Bath",
        "Oven",
        "Vacuum Pump",
        "Fume Hood",
        "Cooling System",
      ],
    },
    {
      id: 5,
      name: "For Organic Reactions",
      items: [
        "Reaction Flask",
        "Separatory Funnel",
        "Reflux Condenser",
        "Distillation Setup",
        "Chromatography Column",
        "Rotary Evaporator",
      ],
    },
    {
      id: 6,
      name: "Chemical Storage",
      items: [
        "Reagent Bottles",
        "Desiccator",
        "Glass Stopper Bottle",
        "Plastic Storage Bottles",
        "Airtight Container",
        "Chemical Safety Cabinet",
      ],
    },
    {
      id: 7,
      name: "Safety Equipment",
      items: [
        "Safety Glasses",
        "Gloves",
        "Lab Coat",
        "Fire Extinguisher",
        "Emergency Shower",
        "Eye Wash Station",
        "Fume Hood",
      ],
    },
  ];

export {toolTipElements};
